# DataSource Config
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/vueblog?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: root
  http:
    encoding:
      charset: utf-8
      force: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  mvc:
    static-path-pattern: /**
  redis:
    database: 0
    host: redis
    port: 6379

shiro-redis:
  enabled: true
  redis-manager:
    host: redis:6379